jm_collections/info/urls.py
from django.conf.urls import patterns, url

from info import views

urlpatterns = patterns(
    '',
    # /info/
    url(r'^$', views.about, name='index'),
)

jm_collections/jm_collections/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve


admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('info.urls', namespace="info")),
    url(r'^books/', include('books.urls', namespace="books")),
    url(r'^reader/', include('reader.urls', namespace="reader")),
    url(r'^signup/', include('signup.urls', namespace="signup"))
)

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

jm_collections/reader/urls.py
from django.conf.urls import patterns, url

from reader import views

urlpatterns = patterns(
    '',
    # /reader/
    url(r'^$', views.reader_home, name='index'),
    # /reader/overview/
    url(r'^overview/$', views.reader_overview, name='overview'),
    # /reader/<reader_id>/details/
    url(r'^(?P<reader_id>\d+)/details/$', views.reader_details,
        name='details'),
    # /reader/add/
    url(r'^add/$', views.reader_add, name='add'),
    # /reader/<reader_id>/edit/
    url(r'^(?P<reader_id>\d+)/edit/$', views.reader_edit, name='edit'),
    # /reader/<reader_id>/delete/
    url(r'^(?P<reader_id>\d+)/delete/$', views.reader_delete,
        name='delete')
)

jm_collections/reader/models.py
from django.db import models


class Reader(models.Model):
    reader_title = models.CharField(max_length=80)
    reader_entry = models.TextField()
    reader_date = models.DateTimeField(auto_now=True)
    reader_author = models.CharField(
        max_length=80,
        default='admin'
    )

    def __unicode__(self):
        return self.reader_title

jm_collections/reader/views.py
import random
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from reader.models import Reader


def get_record_details(reader_id):
    return Reader.objects.get(id=reader_id)


def get_queryset():
    ''' Return the last 5 reader entries. '''

    reader_entries = Reader.objects.order_by('-id')[:5]
    no_of_entries = len(reader_entries)
    if no_of_entries < 5:
        recent_entries = Reader.objects.order_by('-id')[:no_of_entries]
    else:
        recent_entries = reader_entries
    return recent_entries


def get_queryset_all():
    ''' Return all reader entries. '''
    return Reader.objects.order_by('-id')


def check_entries(title, entry):
    ''' Check for valid input or return a message. '''
    params = {}
    if not title:
        params['error_reader_title'] = "Add a title."
    if not entry:
        params['error_reader_entry'] = "Create an entry."

    if params:
        return params


def get_featured():
    ''' return a random featured title, url, and id '''
    # get the reader entries
    entries = get_queryset_all()

    if len(entries) != 0:
        # get all of the available IDs
        reader_ids = []
        for i in entries:
            reader_ids.append(i.id)

        # get 1 random id
        random_id = random.choice(reader_ids)

        # get the title from the random entry
        featured_title = entries.get(id=random_id).reader_title

        params = {
            'title': featured_title,
            'site': 'reader:details',
            'q': random_id
        }

        return params


def reader_home(request):
    author = request.user
    authenticated = False
    featured = get_featured()
    recent_entries = get_queryset()

    if author.is_authenticated():
        authenticated = True

    context = {
        'recent_entries': recent_entries,
        'author': author,
        'authenticated': authenticated,
        'featured_item': featured
    }

    return render(request, 'reader/index.html', context)


def reader_overview(request):
    author = request.user
    authenticated = False
    all_items = get_queryset_all
    featured = get_featured()

    if author.is_authenticated():
        authenticated = True

    context = {
        'all_items': all_items,
        'author': author,
        'authenticated': authenticated,
        'featured_item': featured
    }

    return render(request, 'reader/overview.html', context)


def reader_details(request, reader_id):
    author = request.user
    authenticated = False
    read_details = get_record_details(reader_id)
    featured = get_featured()

    if author.is_authenticated():
        authenticated = True

    context = {'author': author,
               'read_details': read_details,
               'authenticated': authenticated,
               'featured_item': featured
               }

    return render(request, 'reader/details.html', context)


@login_required(login_url='/')
def reader_add(request):
    author = request.user
    authenticated = True
    has_no_sidebar = True

    if request.method == 'POST':
        reader_title = request.POST.get("reader_title", '')
        reader_entry = request.POST.get("reader_entry", '')

        error = check_entries(reader_title, reader_entry)

        if error:
            context = {
                'reader_title': reader_title,
                'author': author,
                'reader_entry': reader_entry,
                'authenticated': authenticated,
                'has_no_sidebar': has_no_sidebar
            }
            context.update(error)
            return render(request, 'reader/read_write.html', context)

        else:
            r = Reader.objects
            r.create(reader_title=reader_title,
                     reader_author=author,
                     reader_entry=reader_entry)

            return redirect('/reader/')

    context = {
        'author': author,
        'authenticated': authenticated,
        'has_no_sidebar': has_no_sidebar
    }

    return render(request, 'reader/read_write.html', context)


@login_required(login_url='/')
def reader_edit(request, reader_id):
    author = request.user
    authenticated = True
    read_details = get_record_details(reader_id)
    has_no_sidebar = True

    if request.method == 'POST':
        read_title = request.POST.get("reader_title", '')
        read_entry = request.POST.get("reader_entry", '')

        error = check_entries(read_title, read_entry)

        if error:
            context = {
                'reader_title': read_title,
                'author': author,
                'reader_entry': read_entry,
                'authenticated': authenticated,
                'has_no_sidebar': has_no_sidebar
            }

            context.update(error)
            return render(request, 'reader/read_edit.html', context)

        else:
            # update the record
            read_details.reader_title = read_title
            read_details.reader_entry = read_entry

            read_details.save()

            return redirect('/reader/')

    context = {
        'read_details': read_details,
        'reader_id': reader_id,
        'authenticated': authenticated,
        'author': author,
        'has_no_sidebar': has_no_sidebar
    }

    return render(request, 'reader/read_edit.html', context)


@login_required(login_url='/')
def reader_delete(request, reader_id):
    author = request.user
    authenticated = True
    read_details = get_record_details(reader_id)
    has_no_sidebar = True

    if request.method == 'POST':

        read_details.delete()

        return redirect('/reader/overview/')

    context = {
        'author': author,
        'read_details': read_details,
        'authenticated': authenticated,
        'has_no_sidebar': has_no_sidebar
    }

    return render(request, 'reader/read_delete.html', context)

jm_collections/templates/reader/details.html
{% extends "global_base.html" %}

{% load humanize %}

{% block heading %}Reader{% endblock %}
{% block subheading %}Details{% endblock%}

{% block page %}
    <!-- Details from the reader -->
    <p>
        <span class="glyphicon glyphicon-time"></span> {{ read_details.reader_date|naturalday }} | {{ read_details.reader_author }}<br>
        <span class="lead"><strong>{{ read_details.reader_title }}</strong></span><br>
        {{ read_details.reader_entry }}
    </p>

    {% if authenticated %}
    <a class="btn btn-primary" href="{% url 'reader:edit' read_details.id %}"><span class="glyphicon glyphicon-pencil"></span> edit</a>
    {% endif %}

{% endblock %}

jm_collections/templates/reader/index.html
{% extends "global_base.html" %}

{% load humanize %}

{% block heading %}Reader{% endblock %}
{% block subheading %}Recent Entries{% endblock%}

{% block page %}

{% if recent_entries %}
    <!-- Recent Reader Entries -->
    {% for entry in recent_entries %}

    <p><span class="glyphicon glyphicon-time"></span> Posted: {{ entry.reader_date|naturalday}} by {{ entry.reader_author }}<br>

    <span class="lead"><a href="{% url 'reader:details' entry.id %}" >{{ entry.reader_title }}</a></span></p>

    <p>{{ entry.reader_entry }}</p>

    <hr>

    {% endfor %}

    {% else %}
        <p>There are no entries.</p>
        {% if authenticated %}
            <p><a href="{% url 'reader:add' %}">add an entry</a></p>
        {% endif %}
    {% endif %}

{% endblock %}

jm_collections/templates/reader/overview.html
{% extends "global_base.html" %}

{% load humanize %}

{% block heading %}Reader{% endblock %}
{% block subheading %}Overview{% endblock%}

{% block page %}
    <!-- All of the reader entries -->
    {% if all_items %}
        <!-- Render all of the titles from the table -->
        {% for item in all_items %}
        <p><span class="glyphicon glyphicon-time"></span> {{ item.reader_date|naturalday }} | {{ item.reader_author }}

        <p><a href="{% url 'reader:details' item.id %}">{{ item.reader_title }}</a><br>
        {{ item.reader_entry }}</p>

        <hr>

        {% endfor %}
    {% else %}
        <p>There are no entries.</p>
        {% if authenticated %}
            <p><a href="{% url 'reader:add' %}">add an entry</a></p>
        {% endif %}
    {% endif %}
{% endblock %}

jm_collections/templates/reader/read_delete.html
{% extends "global_base.html" %}

{% block title %}Delete{% endblock %}

{% block nav %}

<nav>
    <p>
        <a href="{% url 'reader:index' %}">home</a>
        &nbsp;|&nbsp;
        <a href="{% url 'reader:overview' %}">overview</a>
    </p>
</nav>
{% endblock %}

{% block page %}
    <!-- Details from the reader entry -->
    <h1>Delete:</h1>
    <h2>{{ read_details.reader_title }}</h2>

    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete <strong>{{ read_details.reader_title }}</strong>?</p>
        <!-- confirm -->
        <input class="btn btn-danger" type="submit" value="confirm" />
        <!-- cancel -->
        <a href="{% url 'reader:overview' %}">
        <input class="btn btn-default" type="button" value="cancel" /></a>
    </form>
{% endblock %}

jm_collections/templates/reader/read_edit.html
{% extends "global_base.html" %}

{% block title %}Edit{% endblock %}

{% block page %}
    <!-- Details from the publication -->
    <h1>Edit:</h1>

    <form method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td><label>by: &nbsp;&nbsp;</label></td>
                <td>
                    <label>{{ author }} &nbsp;&nbsp;</label>
                </td>
            </tr>

            <tr>
                <td><label>Title&nbsp;&nbsp;</label></td>
                <td>
                    <input type="text" name="reader_title" value="{{ read_details.reader_title }}">
                    <p class="has_warning">{{ error_reader_title }}</p>
                </td>
            </tr>

            <tr>
                <td><label>Entry&nbsp;&nbsp;</label></td>
                <td><textarea rows="10" placeholder="enter text..." name="reader_entry">{{ read_details.reader_entry }}</textarea>
                <p class="has_warning">{{ error_reader_entry }}</p></td>
            </tr>
        </table>


        <!-- update -->
        <div>
            <!-- update -->
            <input class="btn btn-success" type="submit" value="update entry" />
            <!-- cancel -->
            <a href="{% url 'reader:index' %}">
            <input class="btn btn-default" type="button" value="cancel" /></a>
            <!-- delete -->
            <a href="{% url 'reader:delete' reader_id %}">
            <input class="btn btn-default" type="button" value="delete" /></a>

            <p><cite>You will be asked to confirm on the next page.</cite></p>
        </div>
    </form>
{% endblock %}

jm_collections/templates/reader/read_write.html
{% extends "global_base.html" %}

{% block title %}Add{% endblock %}

{% block page %}
    <!-- Details from the publication -->
    <h1>Add:</h1>

    <form method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td><label>by: &nbsp;&nbsp;</label></td>
                <td>
                    <label>{{ author }} &nbsp;&nbsp;</label>
                </td>
            </tr>

            <tr>
                <td><label>Title&nbsp;&nbsp;</label></td>
                <td>
                    <input type="text" name="reader_title" value="{{ reader_title }}">
                    <p class="has_warning">{{ error_reader_title }}</p>
                </td>
            </tr>

            <tr>
                <td><label>Entry&nbsp;&nbsp;</label></td>
                <td><textarea rows="10" placeholder="enter text..." name="reader_entry">{{ reader_entry }}</textarea>
                <p class="has_warning">{{ error_reader_entry }}</p></td>
            </tr>
        </table>


        <!-- update -->
        <div>
            <input class="btn btn-success" type="submit" value="add entry" />
            <!-- cancel -->
            <a href="{% url 'reader:index' %}">
            <input class="btn btn-default" type="button" value="cancel" /></a><br>
        </div>
    </form>
{% endblock %}