jm_collections/books/urls.py
from django.conf.urls import patterns, url

from books import views

urlpatterns = patterns(
    '',
    # /books/
    url(r'^$', views.publications_home, name='index'),
    # /books/<pub_id>/details/
    url(r'^(?P<pub_id>\d+)/details/$', views.publication_details,
        name='details'),
    # /books/overview/
    url(r'^overview/$', views.publication_overview, name='overview'),
    # /books/add/
    url(r'^add/$', views.publication_add, name='add'),
    # /books/<pub_id>/edit/
    url(r'^(?P<pub_id>\d+)/edit/$', views.publication_edit, name='edit'),
    # /books/<pub_id>/delete/
    url(r'^(?P<pub_id>\d+)/delete/$', views.publication_delete,
        name='delete')
)

jm_collections/info/urls.py
from django.conf.urls import patterns, url

from info import views

urlpatterns = patterns(
    '',
    # /info/
    url(r'^$', views.about, name='index'),
)

jm_collections/jm_collections/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve


admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('info.urls', namespace="info")),
    url(r'^books/', include('books.urls', namespace="books")),
    url(r'^reader/', include('reader.urls', namespace="reader")),
    url(r'^signup/', include('signup.urls', namespace="signup"))
)

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

jm_collections/books/models.py
from django.db import models


class Publication(models.Model):
    title = models.CharField(max_length=80)
    author = models.CharField(max_length=80)
    pub_date = models.IntegerField()  # Format ex: 1970
    # The categories list (genres):
    CATEGORIES = (
        ('OTH', 'Other'),
        ('PHI', 'Philosophy'),
        ('FIC', 'Fiction'),
        ('NON', 'Non-Fiction'),
        ('PER', 'Performing Arts'),
        ('VIS', 'Visual Arts'),
        ('WEB', 'Web Authoring'),
        ('COM', 'Computer Science'),
    )
    category = models.CharField(
        max_length=3,
        choices=CATEGORIES,
        default='OTH',
    )

    def __unicode__(self):
        return self.title

jm_collections/books/forms.py
from django import forms


# uploader class
class UploadFileForm(forms.Form):
    file = forms.FileField()

jm_collections/books/views.py
import re
import random
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from books.models import Publication
# from .forms import UploadFileForm


def get_queryset():
    ''' Return the last 5 records '''
    return Publication.objects.order_by('-id')[:5]


def get_record_details(pub_id):
    return Publication.objects.get(id=pub_id)


def get_queryset_all():
    ''' Returns every entry '''
    return Publication.objects.all().order_by('id')


def get_categories():
    ''' Returns a list of the long-name categories '''

    categories = Publication.CATEGORIES
    categories_ln = []

    for c in categories:
        categories_ln.append(str(c[1]))

    return categories_ln


def get_category_code(category):
    ''' Returns the 3-letter code from the long name'''

    categories = Publication.CATEGORIES

    for c in categories:
        if str(c[1]) == category:
            return c[0]


def get_long_category(category):
    ''' Returns a single long-name category from the category code '''

    categories = Publication.CATEGORIES

    for c in categories:
        if str(c[0]) == category:
            return c[1]


def check_date(date):
    ''' Return True if any 4 numbers '''

    date_re = re.compile(r'^[0-9]{4}$')
    return date_re.match(date)


def check_entries(title, author, date):
    ''' Checks for valid input and returns messages '''
    params = {}
    if not title:
        params['error_publication_title'] = "Add a title."
    if not author:
        params['error_publication_author'] = "Add an author."
    if not date:
        params['error_publication_date'] = "Add a publication date."
    elif not check_date(date):
        params['error_publication_date'] = "Enter a proper date (i.e., 1945)"

    if params:
        return params


def get_featured():
    ''' return a random featured title, url, and id '''
    # get the book entries
    pubs = get_queryset_all()

    if len(pubs) != 0:
        # get all of the available IDs
        pub_ids = []
        for i in pubs:
            pub_ids.append(i.id)

        # get 1 random id
        random_id = random.choice(pub_ids)

        # get the title from the random entry
        featured_title = pubs.get(id=random_id).title

        params = {
            'title': featured_title,
            'site': 'books:details',
            'q': random_id
        }

        return params


def publications_home(request):
    author = request.user
    authenticated = False
    recent_entries = get_queryset()
    featured = get_featured()

    # get the full path of the current page
    # book_path = request.get_full_path()

    if author.is_authenticated():
        authenticated = True

    context = {
        'recent_entries': recent_entries,
        'author': author,
        'authenticated': authenticated,
        'featured_item': featured
    }
    return render(request, 'books/index.html', context)


def publication_details(request, pub_id):
    author = request.user
    authenticated = False
    pub_details = get_record_details(pub_id)
    featured = get_featured()

    if author.is_authenticated():
        authenticated = True

    context = {
        'author': author,
        'pub_details': pub_details,
        'authenticated': authenticated,
        'featured_item': featured
    }
    return render(request, 'books/details.html', context)


def publication_overview(request):
    author = request.user
    authenticated = False
    all_items = get_queryset_all()
    featured = get_featured()

    if author.is_authenticated():
        authenticated = True

    context = {
        'author': author,
        'all_items': all_items,
        'authenticated': authenticated,
        'featured_item': featured
    }
    return render(request, 'books/overview.html', context)


@login_required(login_url='/')
def publication_edit(request, pub_id):
    author = request.user
    authenticated = True
    pub = get_record_details(pub_id)
    current_category = pub.category  # ex., VIS
    categories = get_categories()  # ex., [Visual Arts, ..., ...]
    current_category_ln = get_long_category(current_category)
    featured = get_featured()

    if request.method == 'POST':
        title = request.POST.get("publication_title", '')
        pub_author = request.POST.get("publication_author", '')
        pub_date = request.POST.get("publication_date", '')
        category = request.POST.get("publication_category", '')

        error = check_entries(title, pub_author, pub_date)

        if error:
            context = {
                'author': author,
                'pub': pub,
                'categories': categories,
                'authenticated': authenticated,
                'featured_item': featured
            }

            context.update(error)
            return render(request, 'books/pub_edit.html', context)

        else:
            # update the record
            pub.title = title
            pub.author = pub_author
            pub.pub_date = pub_date
            pub.category = get_category_code(category)

            pub.save()

            return redirect('/books/overview/')

    context = {
        'author': author,
        'pub': pub,
        'categories': categories,
        'current_category': current_category,
        'current_category_ln': current_category_ln,
        'authenticated': authenticated,
        'featured_item': featured
    }
    return render(request, 'books/pub_edit.html', context)


@login_required(login_url='/')
def publication_add(request):
    author = request.user
    authenticated = True
    categories = get_categories()
    featured = get_featured()

    if request.method == 'POST':
        title = request.POST.get("publication_title", '')
        pub_author = request.POST.get("publication_author", '')
        pub_date = request.POST.get("publication_date", '')
        chosen_category = request.POST.get("publication_category", '')
        # file_upload = request.POST.get("publication_upload", '')
        # form = UploadFileForm(request.POST, request.FILES)

        error = check_entries(title, pub_author, pub_date)

        if error:
            context = {
                'author': author,
                'publication_title': title,
                'publication_author': pub_author,
                'publication_date': pub_date,
                'chosen_category': chosen_category,
                'categories': categories,
                'authenticated': authenticated,
                'featured_item': featured
            }

            context.update(error)
            return render(request, 'books/pub_add.html', context)

        else:
            # add the new record
            pub = Publication(title=title,
                              author=pub_author,
                              pub_date=pub_date,
                              category=get_category_code(chosen_category))

            pub.save()

            # upload the image file
            # handle_uploaded_file(request.FILES['file'])

            return redirect('/books/overview/')

    context = {
        'author': author,
        'categories': categories,
        'authenticated': authenticated,
        'featured_item': featured
    }
    return render(request, 'books/pub_add.html', context)


@login_required(login_url='/')
def publication_delete(request, pub_id):
    author = request.user
    authenticated = True
    pub = get_record_details(pub_id)
    featured = get_featured()

    if request.method == 'POST':

        pub.delete()

        return redirect('/books/overview/')

    context = {
        'author': author,
        'pub': pub,
        'authenticated': authenticated,
        'featured_item': featured
    }
    return render(request, 'books/pub_delete.html', context)

jm_collections/templates/books/details.html
{% extends "global_base.html" %}

{% block title %}Details{% endblock %}

{% block heading %}Publication Details{% endblock %}

{% block page %}
    <!-- Details from the publication -->
    <ul>
        <li>Title:<strong> {{ pub_details.title }}</strong></li>
        <li>Author:<strong> {{ pub_details.author }}</strong></li>
        <li>Publication Date: {{ pub_details.pub_date }}</li>
        <li>Category: {{ pub_details.category }}</li>
    </ul>
    {% if authenticated %}
    <a class="btn btn-primary" href="{% url 'books:edit' pub_details.id %}"><span class="glyphicon glyphicon-pencil"></span> edit</a>
    {% endif %}
{% endblock %}

jm_collections/templates/books/index.html
{% extends "global_base.html" %}

{% block title %}Home{% endblock %}

{% block heading %}Publications{% endblock %}
{% block subheading %}Recent Titles / Recent Authors{% endblock%}

{% block page %}

    <div class="row">
        <div class="box">
            <div class="col-lg-12">

                <hr>
                {% if recent_entries %}
                    <ul>
                    {% for pub in recent_entries %}
                        <!--  books:title (books is the namespace:title is url)
                                See urls.py for project (not app) -->
                        <li><a href="{% url 'books:details' pub.id %}">
                            {{ pub.title }}</a>
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <p>No titles are available.</p>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>

                {% if recent_entries %}
                    <ul>
                    {% for writer in recent_entries %}
                        <!-- books:author (books is the namespace:author is url) -->
                        <li><a href="{% url 'books:details' writer.id %}">
                            {{ writer.author }}</a>
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <p>No authors are available.</p>
                    {% if authenticated %}
                        <p><a href="{% url 'books:add' %}">add a publication</a></p>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

jm_collections/templates/books/overview.html
{% extends "global_base.html" %}

{% block title %}Overview{% endblock %}

{% block heading %}Publications Overview{% endblock %}

{% block page %}
    <!-- Details from the publication -->

    <!-- Render all of the titles from the table -->
    {% if all_items %}
        <table>
            {% for item in all_items %}
            <tr>
                <td class="pub_id">{{ item.id }}</td>
                <td class="v_rule">&ensp;</td>
                <td class="pub_item">
                    <a href="{% url 'books:details' item.id %}">{{ item.title }}</a>
                </td>
            </tr>
            <tr>
                <td colspan="3">&nbsp;</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>There are no entries.</p>
        {% if authenticated %}
            <p><a href="{% url 'books:add' %}">add a publication</a></p>
        {% endif %}
    {% endif %}
{% endblock %}

jm_collections/templates/books/pub_add.html
{% extends "global_base.html" %}

{% block title %}Add{% endblock %}

{% block nav %}
<nav>
    <p>
        <a href="{% url 'books:index' %}">home</a>
        &nbsp;|&nbsp;
        <a href="{% url 'books:overview' %}">overview</a>
    </p>
</nav>
{% endblock %}

{% block heading %}Add{% endblock %}

{% block page %}
    <!-- Details from the publication -->

    <form method="post">
        {% csrf_token %}

        <table>
            <tr>
                <td><label>Title&nbsp;&nbsp;</label></td>
                <td>
                    <input type="text" name="publication_title" value="{{ publication_title }}">
                    <p class="has_warning">{{ error_publication_title }}</p>
                </td>
            </tr>

            <tr>
                <td><label>Author&nbsp;&nbsp;</label></td>
                <td>
                    <input type="text" name="publication_author" value="{{ publication_author }}">
                    <p class="has_warning">{{ error_publication_author }}</p>
                </td>
            </tr>

            <tr>
                <td><label>Pub date&nbsp;&nbsp;</label></td>
                <td>
                    <input type="text" name="publication_date" value="{{ publication_date }}">
                    <p class="has_warning">{{ error_publication_date }}</p>
                </td>
            </tr>

            <tr>
                <td><label>Category&nbsp;&nbsp;</label></td>
                <td>
                    <select name="publication_category">
                    {% for category in categories %}
                        {% if  category == chosen_category %}
                        <option value="{{ category }}" selected>{{ category }}</option>
                        {% else %}
                        <option value="{{ category }}">{{ category }}</option>
                        {% endif %}
                    {% endfor%}
                    </select>
                </td>
            </tr>
<!--
            <tr>
                <td><label>Image&nbsp;&nbsp;</label></td>
                <td>
                    <input type="file" name="publication_upload" value="browse" accept="image/*">
                    <p class="has_warning">{{ error_image_upload }}</p>
                </td>
            </tr>
 -->
        </table>

        <div>
            <br>
            <!-- add -->
            <input class="btn btn-success" type="submit" value="add publication" />
            <!-- cancel -->
            <a href="{% url 'books:overview' %}">
            <input id="pub-cancel" class="btn btn-default" type="button" value="cancel" /></a><br>
        </div>
    </form>
{% endblock %}

jm_collections/templates/books/pub_delete.html
{% extends "global_base.html" %}

{% block title %}Delete{% endblock %}

{% block nav %}
<nav>
    <p>
        <a href="{% url 'books:index' %}">home</a>
        &nbsp;|&nbsp;
        <a href="{% url 'books:overview' %}">overview</a>
    </p>
</nav>
{% endblock %}

{% block heading %}Delete{% endblock %}

{% block page %}
    <!-- Details from the publication -->
    <h2>{{ pub.title }}</h2>

    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete <strong>{{ pub.title }}</strong>?</p>
        <!-- confirm -->
        <input class="btn btn-danger" type="submit" value="confirm" />
        <!-- cancel -->
        <a href="{% url 'books:overview' %}">
        <input class="btn btn-default" type="button" value="cancel" /></a>
    </form>
{% endblock %}

jm_collections/templates/books/pub_edit.html
{% extends "global_base.html" %}

{% block title %}Edit{% endblock %}

{% block nav %}
<nav>
    <p>
        <a href="{% url 'books:index' %}">home</a>
        &nbsp;|&nbsp;
        <a href="{% url 'books:overview' %}">overview</a>
    </p>
</nav>
{% endblock %}

{% block heading %}Edit{% endblock %}

{% block page %}
    <!-- Details from the publication -->
    <h2>{{ object.title }}</h2>

    <form action="" method="post">
        {% csrf_token %}

        <table>
            <tr>
                <td><label>Title&nbsp;&nbsp;</label></td>
                <td>
                    <input type="text" name="publication_title" value="{{ pub.title }}">
                    <p>{{ error_publication_title }}</p>
                </td>
            </tr>

            <tr>
                <td><label>Author&nbsp;&nbsp;</label></td>
                <td>
                    <input type="text" name="publication_author" value="{{ pub.author }}">
                    <p>{{ error_publication_author }}</p>
                </td>
            </tr>

            <tr>
                <td><label>Pub date&nbsp;&nbsp;</label></td>
                <td>
                    <input type="text" name="publication_date" value="{{ pub.pub_date }}">
                    <p>{{ error_publication_date }}</p>
                </td>
            </tr>

            <tr>
                <td><label>Category&nbsp;&nbsp;</label></td>
                <td>
                    <select name="publication_category">
                    {% for category in categories %}
                        {% if category == current_category_ln %}
                        <option value="{{ category }}" selected>{{ category }}</option>
                        {% else %}
                        <option value="{{ category }}">{{ category }}</option>
                        {% endif %}
                    {% endfor%}
                    </select>
                </td>
            </tr>
<!--
            <tr>
                <td><label>Image&nbsp;&nbsp;</label></td>
                <td>
                    <input type="file" name="publication_upload_path" value="browse" accept="image/*">
                    <p class="has_warning">{{ error_image_upload }}</p>
                </td>
            </tr>
 -->
        </table>

        <div>
            <br>
            <!-- update -->
            <input class="btn btn-success" type="submit" value="update" />
            <!-- cancel -->
            <a href="{% url 'books:overview' %}">
            <input class="btn btn-default" type="button" value="cancel" /><a>
            <!-- delete -->
            <a href="{% url 'books:delete' pub.id %}">
            <input class="btn btn-default" type="button" value="delete" /></a>

            <p><cite>You will be asked to confirm on the next page.</cite></p>
        </div>
    </form>
{% endblock %}