jm_collections/books/urls.py
from django.conf.urls import patterns, url

from books import views

urlpatterns = patterns(
    '',
    # /books/
    url(r'^$', views.publications_home, name='index'),
    # /books/<pub_id>/details/
    url(r'^(?P<pub_id>\d+)/details/$', views.publication_details,
        name='details'),
    # /books/overview/
    url(r'^overview/$', views.publication_overview, name='overview'),
    # /books/add/
    url(r'^add/$', views.publication_add, name='add'),
    # /books/<pub_id>/edit/
    url(r'^(?P<pub_id>\d+)/edit/$', views.publication_edit, name='edit'),
    # /books/<pub_id>/delete/
    url(r'^(?P<pub_id>\d+)/delete/$', views.publication_delete,
        name='delete')
)

jm_collections/info/urls.py
from django.conf.urls import patterns, url

from info import views

urlpatterns = patterns(
    '',
    # /info/
    url(r'^$', views.about, name='index'),
)

jm_collections/jm_collections/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve


admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('info.urls', namespace="info")),
    url(r'^books/', include('books.urls', namespace="books")),
    url(r'^reader/', include('reader.urls', namespace="reader")),
    url(r'^signup/', include('signup.urls', namespace="signup"))
)

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

jm_collections/signup/urls.py
from django.conf.urls import patterns, url

from signup import views

urlpatterns = patterns(
    '',
    # /
    url(r'^login/$', views.user_login, name='login'),
    # /signup/
    # url(r'^signup/$', views.user_signup, name='signup'),
    # /logout/
    url(r'^logout/$', views.user_logout, name='logout')
)

jm_collections/templates/global_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="This is an inventory system and a blog.">
    <meta name="author" content="John Merigliano">

    <title>{% block title %}Collections{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/blog-home.css' %}" rel="stylesheet">

    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type='image/x-icon'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Collections</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="dropdown closed">
                        <a href="{% url 'books:index' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Publications<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'books:index' %}">home</a></li>
                            <li><a href="{% url 'books:overview' %}">overview</a></li>
                        {% if authenticated %}
                            <li><a href="{% url 'books:add' %}" class="button">add a publication</a></li>
                        {% endif %}
                        </ul>
                    </li>
                    <li>
                        <a href="{% url 'reader:index' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Reader<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'reader:index' %}">home</a></li>
                            <li><a href="{% url 'reader:overview' %}">overview</a></li>
                        {% if authenticated %}
                            <li><a href="{% url 'reader:add' %}" class="button">add an entry</a></li>
                        {% endif %}
                        </ul>
                    </li>

                    <li><a href="{% url 'info:index' %}">About</a></li>

                    {% if authenticated %}
                        <li><a href="{% url 'signup:logout' %}">{{ author }} (Logout)</a></li>

                    {% else %}
                        <li><a href="{% url 'signup:login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- content column -->
        {% if has_no_sidebar %}
            <div class="col-md-12">
        {% else %}
            <div class="col-md-8">
        {% endif %}
                {% block column %}

                <h1 class="page-header">{% block heading %}{% endblock %}</h1>
                <h2>{% block subheading %}{% endblock%}</h2>


                {% block page %}{% endblock %}

                {% endblock %}
            </div>

        {% if not has_no_sidebar %}
            <!-- Sidebar Widgets Column -->
            <div class="col-md-4">
                {% block sidebar %}

                <!-- Side Widget Well -->
                <div class="well">
                    <h3>Featured</h3>
                {% if featured_item %}
                    <h4>{% block featured %}<a href="{% url featured_item.site featured_item.q %}">{{ featured_item.title }}</a>{% endblock%}</h4>
                {% else %}
                    <h4>Nothing featured</h4>
                {% endif %}
                </div>

                {% endblock %}
            </div>
        {% endif %}
        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>See the source code on <a href="https://github.com/lautomator/collections" target="_blank">GitHub</a>.</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>